### PR TITLE
Swallow bad requests similar to how we swallow throttle errors

### PR DESCRIPTION
**Pull request by mfine**
Follow a similar handling pattern to the throttler by swallowing Bad Request exceptions in the decider.

### CODE REVIEW

**Review by notoriaga — APPROVED** [review]
Amazing, thank you 🙏

**Review by silverjam — APPROVED** [review]

**Comment by mfine** [comment]
@notoriaga @samvrlewis do either of you want to try this out in sitl? or should we just bring it in?

**Comment by notoriaga** [comment]
> @notoriaga @samvrlewis do either of you want to try this out in sitl? or should we just bring it in?

I'll can give it a go

**Review by samvrlewis — APPROVED** [review]
:pray:

**Comment by notoriaga** [comment]
@mfine Looks good in SITL, thanks!

**Pull request merged**
