### PR TITLE
Debug inputs and outputs

### PR DESCRIPTION
**Pull request by mfine**
Ability to log out the inputs and outputs.

/cc @benjamin0

### CODE REVIEW

**Comment by JoshuaGross** [comment]
I was going to request this after sitting with Ben for a few minutes earlier. Looks good.

**Comment by benjamin0** [comment]
Great! Is there a flag to turn this on/off?

**Comment by mfine** [comment]
Not yet - adding a log-level option.

**Comment by mfine** [comment]
Thought this was going to be quick - but need to backport stuff over from skylark-core to get this functionality. Sorry, will get to it eventually. Beginnings of the changes are here:

https://github.com/swift-nav/wolf/pull/19

**Pull request merged**
